//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubbling7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bubbling7.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubbled with trial BUBBLING UNDRESSER WP App. Please consider buying app..
        /// </summary>
        public static string GeometryExtensions_Paint_Bubbled_with_trial_BUBBLING_UNDRESSER_WP_App__Please_consider_buying_app_ {
            get {
                return ResourceManager.GetString("GeometryExtensions_Paint_Bubbled_with_trial_BUBBLING_UNDRESSER_WP_App__Please_con" +
                        "sider_buying_app_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUBBLING UNDRESSER.
        /// </summary>
        public static string GeometryExtensions_UpdateTile_BUBBLING_UNDRESSER {
            get {
                return ResourceManager.GetString("GeometryExtensions_UpdateTile_BUBBLING_UNDRESSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubbles count.
        /// </summary>
        public static string InfoPage_Bubbles_count {
            get {
                return ResourceManager.GetString("InfoPage_Bubbles_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact author via e-mail.
        /// </summary>
        public static string InfoPage_Contact_author_via_e_mail {
            get {
                return ResourceManager.GetString("InfoPage_Contact_author_via_e_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill color.
        /// </summary>
        public static string InfoPage_Fill_color {
            get {
                return ResourceManager.GetString("InfoPage_Fill_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string InfoPage_GetVersionNumber_unknown {
            get {
                return ResourceManager.GetString("InfoPage_GetVersionNumber_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info+settings.
        /// </summary>
        public static string InfoPage_info_settings {
            get {
                return ResourceManager.GetString("InfoPage_info_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black.
        /// </summary>
        public static string InfoPage_InfoPage_black {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        public static string InfoPage_InfoPage_blue {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brown.
        /// </summary>
        public static string InfoPage_InfoPage_brown {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string InfoPage_InfoPage_current {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cyan.
        /// </summary>
        public static string InfoPage_InfoPage_cyan {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        public static string InfoPage_InfoPage_green {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magenta.
        /// </summary>
        public static string InfoPage_InfoPage_magenta {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string InfoPage_InfoPage_OnLoaded_Version_ {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_OnLoaded_Version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orange.
        /// </summary>
        public static string InfoPage_InfoPage_orange {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purple.
        /// </summary>
        public static string InfoPage_InfoPage_purple {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string InfoPage_InfoPage_red {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transparent.
        /// </summary>
        public static string InfoPage_InfoPage_transparent {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        public static string InfoPage_InfoPage_white {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yellow.
        /// </summary>
        public static string InfoPage_InfoPage_yellow {
            get {
                return ResourceManager.GetString("InfoPage_InfoPage_yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review.
        /// </summary>
        public static string InfoPage_Rate_and_review {
            get {
                return ResourceManager.GetString("InfoPage_Rate_and_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string InfoPage_versionBox_Version_ {
            get {
                return ResourceManager.GetString("InfoPage_versionBox_Version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check how it looks like.
        /// </summary>
        public static string MainPage_Check_how_it_looks_like {
            get {
                return ResourceManager.GetString("MainPage_Check_how_it_looks_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to crop photos before bubbling, use Edit function in Photo Hub..
        /// </summary>
        public static string MainPage_If_you_want_to_crop {
            get {
                return ResourceManager.GetString("MainPage_If_you_want_to_crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imagine!.
        /// </summary>
        public static string MainPage_imagine_ {
            get {
                return ResourceManager.GetString("MainPage_imagine_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MainPage_Info {
            get {
                return ResourceManager.GetString("MainPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load photo from library or shoot.
        /// </summary>
        public static string MainPage_Load_photo_from_library_or_shoot {
            get {
                return ResourceManager.GetString("MainPage_Load_photo_from_library_or_shoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Bubble button to preview bubbles .
        /// </summary>
        public static string MainPage_Press_Bubble_button_to_preview_bubbles_ {
            get {
                return ResourceManager.GetString("MainPage_Press_Bubble_button_to_preview_bubbles_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review.
        /// </summary>
        public static string MainPage_Rate_and_review {
            get {
                return ResourceManager.GetString("MainPage_Rate_and_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save photos from Facebook or other websites hold tap on images in Internet Explorer, then save them to the phone..
        /// </summary>
        public static string MainPage_To_save_photos_from_Facebook {
            get {
                return ResourceManager.GetString("MainPage_To_save_photos_from_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use edit tool to mark dressed areas.
        /// </summary>
        public static string MainPage_Use_edit_tool_to_mark_dressed_areas {
            get {
                return ResourceManager.GetString("MainPage_Use_edit_tool_to_mark_dressed_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use search tool to navigate across image.
        /// </summary>
        public static string MainPage_Use_search_tool_to_navigate_across_image {
            get {
                return ResourceManager.GetString("MainPage_Use_search_tool_to_navigate_across_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can undress anyone in swimsuit with power of your imagination using BUBBLING UNDRESSER. Take a photo, mark dressed areas and you will see virtually naked photos..
        /// </summary>
        public static string MainPage_You_can_undress_anyone {
            get {
                return ResourceManager.GetString("MainPage_You_can_undress_anyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show result.
        /// </summary>
        public static string PhotoEdit_AddFinishButton_Show_result {
            get {
                return ResourceManager.GetString("PhotoEdit_AddFinishButton_Show_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble.
        /// </summary>
        public static string PhotoEdit_CreateMenu_Bubble {
            get {
                return ResourceManager.GetString("PhotoEdit_CreateMenu_Bubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit area.
        /// </summary>
        public static string PhotoEdit_CreateMenu_Edit_area {
            get {
                return ResourceManager.GetString("PhotoEdit_CreateMenu_Edit_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string PhotoEdit_CreateMenu_Search {
            get {
                return ResourceManager.GetString("PhotoEdit_CreateMenu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encircle covered areas.
        /// </summary>
        public static string PhotoEdit_encircle_Encircle_covered_areas {
            get {
                return ResourceManager.GetString("PhotoEdit_encircle_Encircle_covered_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUBBLE UNDRESSER.
        /// </summary>
        public static string PhotoEdit_FinishButtonClick_BUBBLE_UNDRESSER {
            get {
                return ResourceManager.GetString("PhotoEdit_FinishButtonClick_BUBBLE_UNDRESSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a trial version of BUBBLE UNDRESSER. After 2 days of trial use you can only view result via sharing photos on social networks. Would you like to proceed with sharing?.
        /// </summary>
        public static string PhotoEdit_FinishButtonClick_This_is_a_trial_version {
            get {
                return ResourceManager.GetString("PhotoEdit_FinishButtonClick_This_is_a_trial_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move picture.
        /// </summary>
        public static string PhotoEdit_move_Move_picture {
            get {
                return ResourceManager.GetString("PhotoEdit_move_Move_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubbling ....
        /// </summary>
        public static string PhotoEdit_OnBubbleButtonOnClick_Bubbling____ {
            get {
                return ResourceManager.GetString("PhotoEdit_OnBubbleButtonOnClick_Bubbling____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encircle covered areas.
        /// </summary>
        public static string PhotoEdit_Status_Encircle_covered_areas {
            get {
                return ResourceManager.GetString("PhotoEdit_Status_Encircle_covered_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application encountered error processing last request..
        /// </summary>
        public static string PhotoEdit_TouchOnFrameReported_Application_error {
            get {
                return ResourceManager.GetString("PhotoEdit_TouchOnFrameReported_Application_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ViewResult_CreateMenu_Save {
            get {
                return ResourceManager.GetString("ViewResult_CreateMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ViewResult_CreateMenu_Share {
            get {
                return ResourceManager.GetString("ViewResult_CreateMenu_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo {0} saved to camera roll.
        /// </summary>
        public static string ViewResult_savebuttonClick_Photo__0__saved_to_camera_roll {
            get {
                return ResourceManager.GetString("ViewResult_savebuttonClick_Photo__0__saved_to_camera_roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not forget to share interesting results.
        /// </summary>
        public static string ViewResult_Status_Do_not_forget_to_share_interesting_results {
            get {
                return ResourceManager.GetString("ViewResult_Status_Do_not_forget_to_share_interesting_results", resourceCulture);
            }
        }
    }
}
