//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetWireUltimate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetWireUltimate.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim of this game is to power each cell of the net with a branching wire. You have one cell as a power source, other cells are supposed to be connected to the power network..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to drop saved game. Are you sure?.
        /// </summary>
        public static string AreYouSureDrop {
            get {
                return ResourceManager.GetString("AreYouSureDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns count.
        /// </summary>
        public static string ColumnsCount {
            get {
                return ResourceManager.GetString("ColumnsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact author via e-mail at.
        /// </summary>
        public static string ContactAuthor {
            get {
                return ResourceManager.GetString("ContactAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo version maximum level is 4. If you wish to solve harder puzzles you can use free version or buy this app..
        /// </summary>
        public static string DemoConstraint {
            get {
                return ResourceManager.GetString("DemoConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} turns far from perfect.
        /// </summary>
        public static string FarFromPerfect {
            get {
                return ResourceManager.GetString("FarFromPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game info.
        /// </summary>
        public static string GameInfo {
            get {
                return ResourceManager.GetString("GameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirrored mode.
        /// </summary>
        public static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to perfect.
        /// </summary>
        public static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved games.
        /// </summary>
        public static string SavedGames {
            get {
                return ResourceManager.GetString("SavedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hint.
        /// </summary>
        public static string ShowHint {
            get {
                return ResourceManager.GetString("ShowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code available at.
        /// </summary>
        public static string SourceAvailable {
            get {
                return ResourceManager.GetString("SourceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string UnknownForVersion {
            get {
                return ResourceManager.GetString("UnknownForVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use animation.
        /// </summary>
        public static string UseAnimation {
            get {
                return ResourceManager.GetString("UseAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win. And your solution is.
        /// </summary>
        public static string YouWin {
            get {
                return ResourceManager.GetString("YouWin", resourceCulture);
            }
        }
    }
}
